/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/aLUCDZ4wOTs
 */
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import Link from "next/link"
import { Button } from "@/components/ui/button"

export default function Forum({setSelecteCompoId}) {
  return (
    <>
      <main className="container mx-auto p-6">
        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
          <Card className="bg-white rounded-md shadow-md p-6">
            <CardHeader className="flex items-center gap-3">
              <Avatar className="h-9 w-9">
                <AvatarImage alt="User Avatar" src="/placeholder-avatar.jpg" />
                <AvatarFallback>JP</AvatarFallback>
              </Avatar>
              <div className="grid gap-0.5 text-xs">
                <div className="font-medium">Jared Palmer</div>
                <div className="text-gray-500 dark:text-gray-400">Posted on August 24, 2023</div>
              </div>
            </CardHeader>
            <CardContent className="p-4">
              <p className="text-gray-600 dark:text-gray-400">
                Once upon a time, in a far-off land, there was a very lazy king who spent all day lounging on his
                throne. One day, his advisors came to him with a problem: the kingdom was running out of money.
              </p>
              <div className="mt-4">
                <Link className="text-blue-500 hover:underline" href="#">
                  Read more
                </Link>
              </div>
              <div className="mt-4 flex space-x-2">
                <Button className="bg-blue-500 text-white py-2 rounded-md">Modify</Button>
                <Button className="bg-red-500 text-white py-2 rounded-md">Delete</Button>
                <Button className="bg-green-500 text-white py-2 rounded-md">Write</Button>
              </div>
            </CardContent>
          </Card>
          <Card className="bg-white rounded-md shadow-md p-6">
            <CardHeader className="flex items-center gap-3">
              <Avatar className="h-9 w-9">
                <AvatarImage alt="User Avatar" src="/placeholder-avatar.jpg" />
                <AvatarFallback>AB</AvatarFallback>
              </Avatar>
              <div className="grid gap-0.5 text-xs">
                <div className="font-medium">Alexa Black</div>
                <div className="text-gray-500 dark:text-gray-400">Posted on September 1, 2023</div>
              </div>
            </CardHeader>
            <CardContent className="p-4">
              <p className="text-gray-600 dark:text-gray-400">
                Jokester began sneaking into the castle in the middle of the night and leaving jokes all over the place:
                under the king's pillow, in his soup, even in the royal toilet. The king was furious, but he couldn't
                seem to stop Jokester.
              </p>
              <div className="mt-4">
                <Link className="text-blue-500 hover:underline" href="#">
                  Read more
                </Link>
              </div>
              <div className="mt-4 flex space-x-2">
                <Button className="bg-blue-500 text-white py-2 rounded-md">Modify</Button>
                <Button className="bg-red-500 text-white py-2 rounded-md">Delete</Button>
                <Button className="bg-green-500 text-white py-2 rounded-md">Write</Button>
              </div>
            </CardContent>
          </Card>
        </div>
        <div className="mt-8">
          <Button className="w-full bg-blue-500 text-white py-2 rounded-md">Load More</Button>
        </div>
      </main>
    </>
  )
}
